### ISSUE TITLE
what is the version of torch and torchvision?

### ISSUE THREAD

**Issue by szh91** [duwt/OrienMask#1]
by the way, can I use it to test my dataset (not COCO image)?

**Comment by duwt** [comment]
(1) The versions of packages in our running environment are listed below. The torch >= 1.4.0 should be OK and the version of torchvision should be compatible with the version of torch. 
```
- python            3.7.9
- cuda              10.2
- cudnn             7.6.5
- torch             1.6.0
- torchvision       0.5.0
```
(2) Just have a try. :smile:

**Comment by szh91** [comment]
when i run the infer.py, it's error:

RuntimeError: CUDA error: invalid device function
Segmentation fault (core dumped)

**Comment by duwt** [comment]
> when i run the infer.py, it's error:
> 
> RuntimeError: CUDA error: invalid device function
> Segmentation fault (core dumped)

It seems like something wrong about cuda. Make sure pytorch works by running `python -c "import torch; print(torch.cuda.is_available())"`.

**Comment by szh91** [comment]
![image](https://user-images.githubusercontent.com/30435832/123427216-ea080f80-d5f6-11eb-9538-c520a3c5f325.png)

**Comment by duwt** [comment]
I'm not sure what is the exact reason. As indicated by this [link](https://github.com/tianzhi0549/FCOS/issues/173), it may be the version of cudatoolkit is not incorrect during installation for pytorch.
