### ISSUE TITLE
About code detail

### ISSUE THREAD

**Issue by lucasjinreal** [duwt/OrienMask#10]
I am not sure if I understand it right, but I am very confused about this line code:

![image](https://user-images.githubusercontent.com/21303438/131223302-dd645a53-20ca-4dd6-847a-eb5f5ddb3969.png)

in the postprocess abtain masks. Where you multiply `grid_sizes`, which defined as `17x17, 34x34, 68x68` and same as `nH, nW` since you have this code:

![image](https://user-images.githubusercontent.com/21303438/131223328-bb9a6b05-2b94-4a09-8bee-a42f217ebc14.png)

But the boxes wh have this operation before:

![image](https://user-images.githubusercontent.com/21303438/131223343-d8be50d9-994d-4c22-aa0a-22dfb98c79b8.png)

why divide `nH` and `nW` and then multiply it back later. Is that necessary?

**Comment by lucasjinreal** [comment]
I am really confused now, why you name 2 identical variables with 2 different names? And I changed your code to this, I still get correct mask:

![image](https://user-images.githubusercontent.com/21303438/131223455-fbeb50a2-4c80-4e65-a837-96989b011c28.png)

![image](https://user-images.githubusercontent.com/21303438/131223462-9e15c471-f48c-4bc9-8399-8dccf773cd43.png)


![image](https://user-images.githubusercontent.com/21303438/131223450-c3773657-8740-4846-8df4-99facc07ca72.png)

**Comment by duwt** [comment]
Indeed, there are some unnecessary coordinate scaling operations in our implementation. We will add more comments and optimize the codes later. 

Denote the box size as x pixels, the image size as y pixels, the grid size as z pixels, the normalized coordinate is x/y and the so-called "grid coordinate" is x/z. It should be a better way to use the same coordinate scaling during post-processing.
