### ISSUE TITLE
pred_wh not finite

### ISSUE THREAD

**Issue by aswa123** [duwt/OrienMask#13]
(orienmask) swap@pop-os:~/Downloads/OrienMask-master$ CUDA_VISIBLE_DEVICES=0 python train.py     -c orienmask_yolo_coco_544_anchor4_fpn_plus
[DarkNet53] Load pretrained model checkpoints/pretrained/pretrained_darknet53.pth
Set checkpoint directory: checkpoints/OrienMaskAnchor4FPNPlus_0901_125918
2021-09-01 12:59:18,239 
--------------------------------------------------------------------
2021-09-01 12:59:18,240 [EPOCH 1]
2021-09-01 12:59:18,240 Train on epoch 1
  2%|▌                          | 682/29572 [03:55<2:44:38,  2.92it/s, lr=6.40e-04, loss=284.6246]pred_wh not finite
  2%|▌                          | 682/29572 [03:55<2:46:02,  2.90it/s, lr=6.40e-04, loss=284.6246]

**Comment by duwt** [comment]
Refer to https://github.com/duwt/OrienMask/issues/4
