### ISSUE TITLE
About the formula 2 in the paper

### ISSUE THREAD

**Issue by ztt0821** [duwt/OrienMask#16]
Hi, nice work. I am very interested in your paper, which gives me a lot of hints. I am a little confused about the formula 2 in the paper. May I ask why the negative vector is written like this? May I ask can you share your derivation process to help me understand? Thank you very much.

**Comment by duwt** [comment]
Expanding (p_i - b) (green and blue) to reach the border of the valid training area in four directions produces four ratios (yellow and red). It should be both positive and the smaller one as the negative orientation vector defines (red).
![image](https://user-images.githubusercontent.com/86341331/141401650-9798e62a-f7e0-4e25-afb2-ecb53cffcbe4.png)

**Comment by ztt0821** [comment]
Thank you very much for your reply. I have two questions now (1) why the negative smaples represent  "p_i - b" (2) Can I understand the formula (2) negative part like this: the  (p_i - b) is the original negative sample and the (α_i − 1) can play the role as a ratio for the expanding.

**Comment by duwt** [comment]
(1) (p_i - b) is the centrifugal direction as we defined for the negative orientation vector.
(2) The derivation of this expression can be divided as a direction and a magnitude part. But there is actually no "the original negative sample".

**Comment by ztt0821** [comment]
Thank you very much

**Comment by ztt0821** [comment]
Hi, sorry for interrupting you again. I also feel a lot confused about the "Mask Construction" part. I think I didn't fully understand the Orientation Vectors. 

May I ask in the OrienHead, each value in the OrienHead indicates what? I found in the paper 3.2, you said it indicates "stores pixel-wise spatial offsets in horizontal and vertical directions". May I ask what is this offset relative to? Because I saw many  vectors in figure 2. each vector has length and direction, I can't imagine how to show these things in the OrienHead. 

And I also can't understand formula 3(about mask). I think when I understand the Orientation Vectors, I can understand it.

**Comment by duwt** [comment]
An orientation map with the shape (2, H, W) is composed of H*W orientation vectors. Each orientation vector whose coordinate is (x, y) can be denoted as (dx, dy). And the destination of this orientation vector is (x+dx, y+dy). During inference, we use the destination of each orientation vector to determine whether the corresponding pixel belongs to the foreground or not. Hope this description is clear to be understood.

**Comment by ztt0821** [comment]
Thank you for your reply. I still have some questions. I have sent an email (ZJU email) to you. May I ask do you mind I use email to ask the questions?
