### ISSUE TITLE
后处理中anchor_mask

### ISSUE THREAD

**Issue by WYQ-Github** [duwt/OrienMask#18]

**Comment by WYQ-Github** [comment]
你好，请问大佬在后处理中anchor_mask扮演的角色是干嘛用的呀。

**Comment by duwt** [comment]
anchor_mask是借鉴了darknet里面的yolo写法，其含义是给不同尺度的检测头匹配相应的anchor，比如我们的配置文件里面第6、7、8个anchor是第一个检测头的，第3、4、5个anchor是第二个检测头的，以此类推。

https://github.com/pjreddie/darknet/blob/f8f67cd461f20b71fd2ae1a46d04e99ed9f9f51d/cfg/yolov3.cfg#L780-L788

https://github.com/duwt/OrienMask/blob/61a0aa8f6b34c699962f83bb6c8ce557337ea701/config/base.py#L6-L11

**Comment by WYQ-Github** [comment]
懂了，谢谢大佬

**Comment by WYQ-Github** [comment]
您好，为什么要把pred_orien[6,544,544]拓展为[9,2,544,544]？其中的6和后面的9，2分别代表什么呢？

**Comment by duwt** [comment]
nA=3表示每个检测头有3个anchor，对应有[3, 2, H, W]的方向图，因为共有3个检测头，所以总的方向图是[3*3, 2, H, W]，其中2表示每个方向向量有两个分量，具体解释可参考论文。
