### ISSUE TITLE
compare with SOLOv2

### ISSUE THREAD

**Issue by zhangming8** [duwt/OrienMask#2]
Hi, thanks for your great work.
Could you compare OrienMask with SOLOv2 about mAP and FPS

**Comment by duwt** [comment]
The comparison between OrienMask with SOLOv2-Lite is reported in Table 6 of our [paper](https://arxiv.org/abs/2106.12204).
```
Method        FPS    AP
SOLOv2-Lite   39.6   33.7
OrienMask     41.9   34.5
```
