### ISSUE TITLE
postprocess recover mask

### ISSUE THREAD

**Issue by lyxbyr** [duwt/OrienMask#20]
Thanks your works! 
  I has confused about recover mask, and got orien[9, 2, H, W] convert to Tensor [1, 18,  H, W] in tensorrt , I has recover boxs in origin image, ,the x<bbox.width*orien_threshold && y<  bbox.height* orien_threshold in code , I just need to iterate through this 18-channel picture (Tensor [1, 18, H, W] )to filter out the pixel values?

**Comment by duwt** [comment]
Sorry that I cannot exactly understand what you mean. For each instance, the mask construction procedure is based on the paired 2-channel orientation map.

**Comment by lyxbyr** [comment]
`

**Comment by duwt** [comment]
只进行reshape操作，确保其他操作保持一致就行。
