### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by aoko-sys** [duwt/OrienMask#3]
作者您好！
我在利用您开源的代码训练coco数据集的时候，训练到一半突然报错，您看看这是什么问题？
![微信图片_20210811095655](https://user-images.githubusercontent.com/52449394/128958237-6ca97fe6-b54a-4497-8555-a864dbfce560.jpg)

**Comment by duwt** [comment]
非常抱歉，你可以把学习率warm-up的步数从500改为1000，这会提升训练的稳定性。
https://github.com/duwt/OrienMask/blob/fce422f546f7ac83305208d98a8cef590902018f/config/base.py#L248-L256

**Comment by aoko-sys** [comment]
@duwt 作者您好，我按您的提示进行更了，warmup_iter=500----》1000 or 1500。都会报之前一样的错误。请问还有更好的解决办法吗？我是双2080ti，ubuntu20.4系统

**Comment by duwt** [comment]
@aoko-sys 我在这个配置下试过好几次都没有出现error，我也不太清楚具体原因是什么，使用的版本是cuda 10.2，cudnn 7.6.5，torch 1.6.0。另外我注意到你的一个epoch迭代次数是29572，是不是改了batch size，这样的话会影响训练稳定性。

**Comment by aoko-sys** [comment]
我只有两张卡，如果我batch size按您默认的batch_size=8,我的内存是不够的，所以我改成了2



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: duwt ***@***.***&gt;
发送时间: 2021年8月14日 09:56
收件人: duwt/OrienMask ***@***.***&gt;
抄送: aoko-sys ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[duwt/OrienMask] 训练报错 (#3)





 
@aoko-sys 我在这个配置下试过好几次都没有出现error，我也不太清楚具体原因是什么，使用的版本是cuda 10.2，cudnn 7.6.5，torch 1.6.0。另外我注意到你的一个epoch迭代次数是29572，是不是改了batch size，这样的话会影响训练稳定性。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by duwt** [comment]
12G内存的话应该是可以的，如果内存不够可以根据readme里面写的保持n_gpu\*batch_size\*accumulate=16，这里的accumulate指的是累计多次梯度进行回传。

**Comment by aoko-sys** [comment]
我安装您的建议更改成如下：batch_size=4，n_gpu=2，accumulate=2，可以训练到5066步了，但是最后还是报错，退出运行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: duwt ***@***.***&gt;
发送时间: 2021年8月14日 10:35
收件人: duwt/OrienMask ***@***.***&gt;
抄送: aoko-sys ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[duwt/OrienMask] 训练报错 (#3)





 
12G内存的话应该是可以的，如果内存不够可以根据readme里面写的保持n_gpu*batch_size*accumulate=16，这里的accumulate指的是累计多次梯度进行回传。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aoko-sys** [comment]
我之前pytorch是1.9.0的，我更改成1.6.0之后，直接不能训练了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: duwt ***@***.***&gt;
发送时间: 2021年8月14日 09:56
收件人: duwt/OrienMask ***@***.***&gt;
抄送: aoko-sys ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[duwt/OrienMask] 训练报错 (#3)





 
@aoko-sys 我在这个配置下试过好几次都没有出现error，我也不太清楚具体原因是什么，使用的版本是cuda 10.2，cudnn 7.6.5，torch 1.6.0。另外我注意到你的一个epoch迭代次数是29572，是不是改了batch size，这样的话会影响训练稳定性。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aoko-sys** [comment]
您好，方便加个微信嘛？1064435762（qq，wechat）都可以



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: duwt ***@***.***&gt;
发送时间: 2021年8月14日 10:35
收件人: duwt/OrienMask ***@***.***&gt;
抄送: aoko-sys ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[duwt/OrienMask] 训练报错 (#3)





 
12G内存的话应该是可以的，如果内存不够可以根据readme里面写的保持n_gpu*batch_size*accumulate=16，这里的accumulate指的是累计多次梯度进行回传。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by duwt** [comment]
@aoko-sys 我试着跑了这一配置组合下的实验，确实会时不时出现报错，我暂时无法解释为什么会出现这种情况，之后有结果会及时更新。在保持n_gpu\*batch_size\*accumulate=16的条件下，accumulate=1的实验稳定性会高很多，实在是内存受限的话建议调小方向向量的损失权重，从原来的20改为15，这在我们的实验中会有一定的性能下降。

**Comment by aoko-sys** [comment]
请问这个方向向量在什么py文件哪一行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: duwt ***@***.***&gt;
发送时间: 2021年8月15日 14:56
收件人: duwt/OrienMask ***@***.***&gt;
抄送: aoko-sys ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[duwt/OrienMask] 训练报错 (#3)





 
@aoko-sys 我试着跑了这一配置组合下的实验，确实会时不时出现报错，我暂时无法解释为什么会出现这种情况，之后有结果会及时更新。在保持n_gpu*batch_size*accumulate=16的条件下，accumulate=1的实验稳定性会高很多，实在是内存受限的话建议调小方向向量的损失权重，从原来的20改为15，这在我们的实验中会有一定的性能下降。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by duwt** [comment]
@aoko-sys 配置文件L208后两个权重，可以设置为15甚至10。
https://github.com/duwt/OrienMask/blob/61a0aa8f6b34c699962f83bb6c8ce557337ea701/config/base.py#L196-L210
