### ISSUE TITLE
bug in infer.py

### ISSUE THREAD

**Issue by hank-sunday** [duwt/OrienMask#5]
when i run infer.py, there is an error. cause by util/visualizer.py

x1,y1,x2,y2=bbox

should be:

x1,y1,x2,y2=bbox.cpu().numpy().tolist()

**Comment by duwt** [comment]
There is no error in our platform. Your modification has better compatibility with different versions of packages and I will fix the bug later. Thank you.

**Comment by hank-sunday** [comment]
OH ，i see , thanks
