### ISSUE TITLE
训练自定义的数据集

### ISSUE THREAD

**Issue by aoko-sys** [duwt/OrienMask#7]
作者您好，请问训练自定义数据集，标注形式是用labelme标注成语义分割的形式，还是使用labelimg标注成目标检测的形式？

**Comment by duwt** [comment]
参考COCO的标注格式https://cocodataset.org/#format-data
然后使用utils/prepare_dataset.py来转换格式

**Comment by aoko-sys** [comment]
您好！为什么您这篇实例分割的代码会用到anchor个东西呢？我标注的数据并不是（x，y，w，h）目标检测数据类型

**Comment by duwt** [comment]
这属于基于检测的实例分割方法，像Mask R-CNN也是在检测器的基础上做的实例分割。
如果只标注了mask，可以计算出xywh，可以参考https://github.com/cocodataset/cocoapi。

**Comment by aoko-sys** [comment]
我想问一下，最后分割结果输出（mask和boundingbox），那么其中boundingbox是怎么获取的？

**Comment by duwt** [comment]
box是检测器的输出头预测出来的，在这个基础上根据方向图确定mask。
