### ISSUE TITLE
About code detail

### ISSUE THREAD

**Issue by lucasjinreal** [duwt/OrienMask#8]
what's the gt_inst_mask dimension here: https://github.com/duwt/OrienMask/blob/61a0aa8f6b34c699962f83bb6c8ce557337ea701/eval/orienmask_yolo_loss.py#L259 ?

is it same wh with original image size or just the mask patch same wh with box?

**Comment by duwt** [comment]
The shape of `gt_inst_mask` is the same as the input image size.

**Comment by lucasjinreal** [comment]
@duwt Oh, in such case, what should I do if I am using detectron2 preprocess way to train OrienMask?
I mean, using rectangle input and input batch will add padding if input images hw are different.

Then how to do with masks of every instance?

**Comment by duwt** [comment]
The ground truth masks should be transformed concurrently when preprocessing the input image, such as resizing, padding, cropping, and so on. In a word, make sure that masks are consistent with the input image.

**Comment by lucasjinreal** [comment]
@duwt  thanks for your reply, but this is not my question.  My question is, if my image is padded in preprocess for batchs, but the mask is not, can I obtain these masks using boxes correctly? (Since even added padding, the boxes coordinates doesn't effected, so that masks can indexed with boxes coordinates)
Does build_targets support this step?

**Comment by duwt** [comment]
What's the meaning of "masks can indexed with boxes coordinates"? If you do not pad masks along with the image, the padding information must be recorded for building orientation map targets. The current `build_targets` function only supports matched input and ground truth. For further development, it can be flexible but should follow the principle that masks must be consistent with the input image.

**Comment by lucasjinreal** [comment]
@duwt OK solved the problem, just make it can work with padding input as well as rectangle input.
